### ISSUE TITLE
npm package includes .git

### ISSUE THREAD

**Issue by rotsee** [papandreou/node-cldr#101]
I seems like this issue has surfaced again: https://github.com/papandreou/node-cldr/issues/96

Workaround: Remove the `node_modules/cldr/.git/` folder before running `npm install` or `npm upgrade`. You can add the following to `package.json` to have it deleted automatically, or for it to work on e.g. Heroku or other cloud platforms:
```
"scripts": {
  "preinstall": "rm -rf node_modules/cldr"
}
```

**Comment by papandreou** [comment]
Argh, thanks for noticing, what an annoying bug. I tried publishing a new version with npm 6.9.0, but it still happened. Then I gave up and just deleted my local `feature/changelog` branch, and that helped.

Fixed in 5.5.3.
