### ISSUE TITLE
renderSpelloutCardinal doesn't handle decimal digits well

### ISSUE THREAD

**Issue by rotsee** [papandreou/node-cldr#102]
I haven't investigated, but `renderSpelloutCardinal` seems to behave differently for numbers -1 < n < 1:

```
> cldr.extractRbnfFunctionByType('en_GB').renderSpelloutCardinal(1.6)
'one point six'
> cldr.extractRbnfFunctionByType('en_GB').renderSpelloutCardinal(0.6)
'zero'
```

...and there is also something fishy going on here:

```
> cldr.extractRbnfFunctionByType('en_GB').renderSpelloutCardinal(2.009)
'two point nine'
```

**Comment by papandreou** [comment]
Hmm, yeah, that does look a bit weird. Better reread https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/classRuleBasedNumberFormat.html

There's an `x.x` rule: https://github.com/papandreou/node-cldr/blob/d076057bb15b9d9d332bfdc17d61738b55aaf896/3rdparty/cldr/common/rbnf/en.xml#L66

... but I don't really see anything about leading zeroes in the fractional part. Where was that reference implementation with a web UI again?

**Comment by rotsee** [comment]
Here's the reference implementation: https://st.unicode.org/cldr-apps/numbers.jsp

**Comment by papandreou** [comment]
Hmm, yeah, we're clearly doing something wrong 😅 

![Screen Shot 2019-12-16 at 15 06 48](https://user-images.githubusercontent.com/373545/70913159-c0d7ed80-2015-11ea-8759-8fcbf71de0e3.png)

**Comment by papandreou** [comment]
Oh:

> `x.x: << point >>;`
> This rule is used for all positive non-integers (negative non-integers pass through the negative-number rule first and then through this rule). Here, the << token refers to the number's integral part, and the >> to the number's fractional part. The fractional part is formatted as a series of __single-digit numbers__ (e.g., 123.456 would be formatted as "one hundred twenty-three point four five six").

(my emphasis)
