### ISSUE TITLE
Dependency <xmldom> 0.6.0 has security vulnerability

### ISSUE THREAD

**Issue by be5invis** [papandreou/node-cldr#153]
https://www.npmjs.com/advisories/1769

> ## Impact
> xmldom versions 0.6.0 and older do not correctly escape special characters when serializing elements removed from their ancestor. This may lead to unexpected syntactic changes during XML processing in some downstream applications.
> 
> ## Patches
> Update to 0.7.0
> (see issue #271 for the status of publishing the version to npm or join for Q&A/discussion #270 until it's resolved)

**Comment by papandreou** [comment]
It doesn't really matter, as xmldom is not used for serialization in this project.

Also, [xmldom 0.7.0 has not been published](https://github.com/xmldom/xmldom/issues/271), so it's not actionable right now.

**Comment by be5invis** [comment]
`xmldom` 0.7.1 has been published.

**Comment by papandreou** [comment]
Okay, fixed in 7.1.1.
