### ISSUE TITLE
`Numeric literal whose value is NaN` for some locales

### ISSUE THREAD

**Issue by rassie** [papandreou/node-cldr#174]
Spun out of https://github.com/papandreou/node-cldr/issues/145, which described a different problem but the same symptom: 

```
> cldr.extractRbnfFunctionByType("ru")
Uncaught Error: Numeric literal whose value is NaN
```

I've made a loop over all locales and apparently it only affects `ru` locales and its variations (`ru_kz`, `ru_ru`, `ru_md`, `ru_ua`, `ru_kg` and `ru_by`).

Any idea what this could be?

**Comment by papandreou** [comment]
Looks like we choke on this syntax: https://github.com/papandreou/node-cldr/blob/25ba30271adce04d164868ca97a2e1dd70b4de6a/3rdparty/cldr/common/rbnf/ru.xml#L24

It goes wrong here, where we end up `parseInt('x.x')`, which returns `NaN`: https://github.com/papandreou/node-cldr/blob/25ba30271adce04d164868ca97a2e1dd70b4de6a/lib/CldrRbnfRuleSet.js#L416

**Comment by rassie** [comment]
Thanks!
