### ISSUE TITLE
Update CLDR to the latest version?

### ISSUE THREAD

**Issue by slavafomin** [papandreou/node-cldr#24]
I've just noticed, that CLDR data is contained locally within the repository and is outdated.

Are you planning to update it? Is there an automatic script to update it or are you doing it manually?

Thanks!

**Comment by papandreou** [comment]
I usually do something like this:

```
rm -r 3rdparty && mkdir -p 3rdparty/cldr && (cd 3rdparty/cldr && unzip /path/to/new/core.zip) && git add 3rdparty && git commit -m "Updated CLDR to release XX"
```

When there are no major data format changes, it's usually just a matter of updating a test here and there to match the data changes.

I tried updating to CLDR 26, then to 27.0.1, and it seems fine, so I just released it as 3.0.0.

**Comment by slavafomin** [comment]
Oh, thanks )

By the way, why have you decided to release a major update? Does it break compatibility with the previous version `2.x`?

**Comment by papandreou** [comment]
I guess it was a "defensive" major version bump as I don't know exactly what's in CLDR releases 26 and 27, and the test coverage isn't so great.

**Comment by slavafomin** [comment]
Ok, I see. Thanks! )
