### ISSUE TITLE
Updating pegjs dependency

### ISSUE THREAD

**Issue by mwoc** [papandreou/node-cldr#30]
pegjs v0.7.0 uses util.puts, which is deprecated in nodejs v0.12 and higher. They fixed that in https://github.com/pegjs/pegjs/commit/de1704f007523da4e8309d799adc24e9adcb0ea7 which is part of v0.9.0, but between these versions many seemingly backward-incompatible changes were landed, specifically this one is breaking for us:
https://github.com/pegjs/pegjs/commit/86769a6c5c46efeb77020d91c0e4837020101b6d

e.g.:

1) CldrPluralRule should encode some assorted test cases correctly:
     UnexpectedError: 
expected 'n is 4 or n is not 6' to encode to 'n === 4 || n !== 6'

-n === NaN || n !== NaN
+n === 4 || n !== 6
      at Function.<anonymous> (test/CldrPluralRule.js:10:9)
      at Context.<anonymous> (test/CldrPluralRule.js:14:9)

Let's investigate if we can easily fix this or have to report it to pegjs devs.

**Comment by papandreou** [comment]
Thanks for narrowing it down. Based on that commit it was pretty easy to fix it in the grammar.

**Comment by papandreou** [comment]
Released in 3.5.2.
