### ISSUE TITLE
Publish without .git

### ISSUE THREAD

**Issue by gajus** [papandreou/node-cldr#96]
Currently trying to re-installing cldr is throwing an error:

```
npm ERR! path /Users/gajus/Documents/dev/applaudience/cinema-data-scraper-sources/node_modules/cldr
npm ERR! code EISGIT
npm ERR! git /Users/gajus/Documents/dev/applaudience/cinema-data-scraper-sources/node_modules/cldr: Appears to be a git repo or submodule.
npm ERR! git     /Users/gajus/Documents/dev/applaudience/cinema-data-scraper-sources/node_modules/cldr
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gajus/.npm/_logs/2019-08-15T10_09_29_257Z-debug.log

```

This is because `./cldr` was published with `.git` folder.

**Comment by papandreou** [comment]
Hmm, this is really weird. The `.git` folder wasn't included in 5.3.0, and I just published 5.4.1, which doesn't either.

Maybe I accidentally published 5.4.0 with a version of npm that had this bug: https://github.com/npm/npm/issues/20213

Anyway, if you update to 5.4.1, the problem should go away. Thanks for reporting!
