### ISSUE TITLE
Consider using gzip

### ISSUE THREAD

**Issue by gajus** [papandreou/node-cldr#99]
The current project size is 175.5 MiB. I suggest compressing individual ./3rdparty files using gzip.  This reduces project size to just under 22MiB. Meanwhile, since individual files are small, they can be decompressed at runtime and memoized.

**Comment by papandreou** [comment]
This package is really only meant to be consumed as a dev dep, and mostly for packages that publish the CLDR data in smaller chunks. The [ander](https://github.com/papandreou/ander) package is an example of that. Is there any way that approach could work for your package?

Compressing the files could be an option, but it wouldn't affect the size of the downloaded tarball, of course?

**Comment by gajus** [comment]
> Compressing the files could be an option, but it wouldn't affect the size of the downloaded tarball, of course?

The problem is the Docker images. This increases Docker image by ~125MB.

**Comment by gajus** [comment]
In my cases I worked around by extracting just the data I need from the package.

https://github.com/gajus/extract-date/commit/890e3c1d512e9c073fe50218c56ed1a66f6aad97#diff-01994488c699366e7146092d8327cada

**Comment by papandreou** [comment]
Okay, great that you were able to sort it out like that!

I think we would accept a PR for gzipping the cldr files if it's not too invasive.
